tasks:
  - name: Setup TYPO3
    init: |
      cp .env.gitpod .env || true
      chmod +x gitpod-setup.sh
      ./gitpod-setup.sh
    command: |
      symfony serve --dir=public --no-tls --port=8000

ports:
  - port: 8000
    onOpen: open-preview
